#pragma once
#include <Arduino.h>
namespace vibrant {
static const char HOME_PAGE_HEADER[] PROGMEM =
    "<!doctype html><html><head><meta "
    "charset='utf-8'><title>VIBRANT</"
    "title><style>body{font-family:Arial,sans-serif;margin:20px;}table{border-"
    "collapse:collapse;width:100%;}th,td{border:1px solid "
    "#ddd;padding:8px;}th{background:#f5f5f5;}a,button{padding:4px "
    "8px;margin:2px;}.output-toggle{border:1px solid #999;border-radius:999px;"
    "min-width:64px;padding:8px 16px;font-weight:bold;cursor:pointer;}"
    ".output-on{background:#d3d3d3;color:#222;}.output-off{background:#fff2b2;"
    "color:#222;}input[type='checkbox']{width:18px;height:18px;}.action-"
    "banner{background:#fff3cd;border:1px solid "
    "#ffc107;padding:10px;margin:10px "
    "0;border-radius:4px;}</style><script>\nvar _wasRunning=false;\nfunction "
    "pollStatus(){\n  fetch('/action/status').then(function(r){return "
    "r.json();})\n  .then(function(d){\n    var "
    "div=document.getElementById('action-status');\n    if(d.running){\n      "
    "var detail=d.cyclesRemaining>0?' (cycles remaining: "
    "'+d.cyclesRemaining+')':'';\n      div.innerHTML='<div "
    "class=\"action-banner\"><strong>Action running on '+(d.allOutputs?'all "
    "outputs':'output '+(d.idx+1))+': '+d.phase+detail+'</strong>'      +' "
    "&nbsp; <form method=\"post\" action=\"/action/cancel\" "
    "style=\"display:inline;\"><button "
    "type=\"submit\">Cancel</button></form></div>';\n    } else {\n      "
    "div.innerHTML='';\n      if(_wasRunning){window.location.reload();}\n    "
    "}\n    _wasRunning=d.running;\n  "
    "}).catch(function(){});\n}\nsetInterval(pollStatus,3000);\n</script></"
    "head><body><h1>VIBRANT Output Control</h1><p>Version: ";
static const char SETTINGS_PAGE_HEADER[] PROGMEM =
    "<!doctype html><html><head><meta charset='utf-8'><title>VIBRANT "
    "Settings</"
    "title><style>body{font-family:Arial,sans-serif;margin:20px;}fieldset{"
    "margin-bottom:16px;}label{display:block;margin:6px "
    "0;}table{border-collapse:collapse;width:100%;}th,td{border:1px solid "
    "#ddd;padding:8px;}th{background:#f5f5f5;}input,select{width:100%;padding:"
    "6px;box-sizing:border-box;}button{padding:8px "
    "10px;margin-right:8px;}.bulk-actions{margin:10px 0;}.settings-nav a{"
    "display:inline-block;margin:4px 8px 12px 0;}.settings-nav .current{"
    "font-weight:bold;}.page-intro{color:#555;}</style>";
static const char SETTINGS_PAGE_SCRIPT[] PROGMEM =
    "<script>\nfunction parseNameSequence(template){\n  const "
    "match=template.match(/#(\\d+)/);\n  if(!match)return null;\n  return "
    "{token:match[0],start:parseInt(match[1],10)};\n}\nfunction "
    "sequentialNameValue(template,sequence,index){\n  if(!sequence)return "
    "template;\n  return "
    "template.replace(sequence.token,'#'+(sequence.start+index));\n}\nfunction "
    "copyFirstModelToAll(){\n  const form=document.getElementById('device-form');\n  "
    "if(!form)return;\n  const first=form.elements['model_0'];\n  "
    "if(!first)return;\n  const "
    "count=form.querySelectorAll(\"input[name^='model_']\").length;\n  for(let "
    "i=1;i<count;i++){\n    const field=form.elements['model_'+i];\n    "
    "if(field)field.value=first.value;\n  }\n}\nfunction "
    "copyFirstManufacturerToAll(){\n  const form=document.getElementById('device-form');\n  "
    "if(!form)return;\n  const first=form.elements['manufacturer_0'];\n  "
    "if(!first)return;\n  const "
    "count=form.querySelectorAll(\"input[name^='manufacturer_']\").length;\n  "
    "for(let i=1;i<count;i++){\n    const "
    "field=form.elements['manufacturer_'+i];\n    "
    "if(field)field.value=first.value;\n  }\n}\nfunction "
    "copyFirstNameToAll(){\n  const form=document.getElementById('device-form');\n  "
    "if(!form)return;\n  const first=form.elements['name_0'];\n  "
    "if(!first)return;\n  const template=first.value;\n  const "
    "sequence=parseNameSequence(template);\n  const "
    "count=form.querySelectorAll(\"input[name^='name_']\").length;\n  for(let "
    "i=0;i<count;i++){\n    const field=form.elements['name_'+i];\n    "
    "if(field)field.value=sequentialNameValue(template,sequence,i);\n  "
    "}\n}\nfunction reverseGpioAssignments(){\n  const "
    "form=document.getElementById('device-form');\n  if(!form)return;\n  const "
    "fields=Array.from(form.querySelectorAll(\"select[name^='pin_']\"));\n  "
    "const values=fields.map((field)=>field.value).reverse();\n  "
    "fields.forEach((field,index)=>{field.value=values[index];});\n}\nfunction "
    "clearAllFieldsExceptOutput(){\n  const form=document.getElementById('device-form');\n  "
    "if(!form)return;\n  "
    "form.querySelectorAll(\"input[name^='manufacturer_'],input[name^='model_']"
    ",input[name^='name_']\").forEach((field)=>{field.value='';});\n}\n</"
    "script>";
} // namespace vibrant
